[project]
name = "xia"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "stable-baselines3>=2.0.0",
    "gymnasium[box2d,classic-control]>=1.2.3",
    "torch>=2.0.0",
    "numpy>=2.0.0",
    "tensorboard>=2.0.0",
    "ipykernel>=6.29.0",
    "matplotlib>=3.8.0",
    "opencv-python>=4.8.0",
    "shap>=0.44.0",
    "pygame-ce>=2.5.0",
    "pip>=26.1.1",
    "notebook>=7.5.6",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu126", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true
